apiVersion: v1
kind: Service
metadata:
  name: expose-app
  namespace: demo
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
  selector:
    app: samples-web
