apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-pod-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-pod-sa
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-pod-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: create-pod-sa
subjects:
  - kind: ServiceAccount
    name: create-pod-sa
