apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: create-pod-sa # A service account has privileges to create a Pod
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: webhook-pod-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: v1
              kind: Pod
              metadata:
                generateName: argocd-imager-updater-
              spec:
                restartPolicy: Never
                serviceAccountName: argocd-image-updater
                containers:
                  - name: argocd-image-updater
                    image: quay.io/argoprojlabs/argocd-image-updater:v0.12.2
                    command:
                      - /usr/local/bin/argocd-image-updater
                      - run
                      - --once
                      - --warmup-cache=false
                    env:
                      - name: ARGOCD_TOKEN
                        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJqZWZmOmFwaUtleSIsIm5iZiI6MTcxNTYzMzUwOCwiaWF0IjoxNzE1NjMzNTA4LCJqdGkiOiI0YTMxZjhjZC01NTE1LTQwZTAtYjQ3OS00YTEzZmViZDgzYmUifQ._gWsS-l-c0HMH32Gr798BNsgHvTUQJkDsXF3bM4gfPw"
                      - name: ARGOCD_INSECURE
                        value: "true"
                      - name: IMAGE_UPDATER_LOGLEVEL
                        value: "debug"
          parameters:
            - src:
                dependencyName: test-dep
              dest: spec.containers.0.args.0
