apiVersion: v2
name: samples
description: Helm Chart for the web application of Testkube Samples.
type: application
version: 0.1.0
dependencies:
  - name: common
    version: 2.13.3
    repository: https://charts.bitnami.com/bitnami
