apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: hello-api-hurl
  namespace: testkube
spec:
  content:
    git:
      uri: https://github.com/kubeshop/testkube-samples
      revision: main
      paths:
        - api
  container:
    workingDir: /data/repo/api
  steps:
    - name: Run test
      run:
        image: ghcr.io/orange-opensource/hurl:4.2.0
        env:
          - name: "HURL_origin"
            value: "http://localhost:8080"
        shell: |
          npm run start &
          sleep 2
          hurl --test --glob tests/*.hurl
    # - name: Sleep
    #   condition: always
    #   run:
    #     image: ghcr.io/orange-opensource/hurl:4.2.0
    #     command: ["sleep", "infinity"]
