name: Build Tag

on:
  push:
    tags:
      - "dashboard/*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: depot/setup-action@v1

      - uses: depot/build-push-action@v1
        with:
          context: ./apps/web
          project: 60kpnpdhwx
          # ref is "ref/tags/dashboard@0.1.0" so we want to take everything after @
          # see https://stackoverflow.com/questions/9532654/expression-after-last-specific-character
          tags: wito3030/testkube-samples:${GITHUB_REF##*@}
          platforms: linux/amd64,linux/arm64
          push: ${{github.ref == 'refs/heads/main'}}
