name: Prebuild

on:
  push:
    branches:
      - "*"
      - "!main"

jobs:
  prebuild:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: depot/setup-action@v1
      - uses: depot/build-push-action@v1
        with:
          context: ./apps/web
          project: 60kpnpdhwx
          platforms: linux/amd64,linux/arm64
