name: Release candidate tag

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: "${{ secrets.CHANGESET_GH_DEPLOY_TOKEN }}"
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: "6.x"
          includePrerelease: true

      - name: Execute GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0

      - name: Create tag for release candidate
        id: tag
        run: echo "value=dashboard@${{ steps.gitversion.outputs.semVer }}" >> "$GITHUB_OUTPUT"

      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{steps.tag.outputs.value}}',
              sha: context.sha
            })
